# Generated by Django 5.2.13 on 2026-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeluControl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Userr',
            new_name='Owner',
        ),
        migrations.AddField(
            model_name='product',
            name='Character',
            field=models.CharField(default=0, help_text='имя персонажа', max_length=200),
            preserve_default=False,
        ),
    ]
